### ISSUE TITLE
Doesn't add semicolon to end of file

### ISSUE THREAD

**Issue by keven425** [browserify/browserify-website#26] opened 2014-08-25 23:15 UTC
This will throw error when concatenating browserified file with other angular modules.

e.g.

Uncaught Error: Cannot find module 'function (z,f,T){'use strict';f.module("ngAnimate",["ng"]).factory("$$animateReflow",["$window","$timeout","$document",function(f,h,d){var n=f.requestAnimationFrame||f.webkitRequestAnimationFrame||function(d){ret...<omitted>...}'

**Comment by goto-bus-stop** [comment] 2018-02-09 14:08
dupe of https://github.com/browserify/browserify/issues/1351

**Closed by goto-bus-stop** 2018-02-09 14:08 UTC
